### ISSUE TITLE
后续会考虑支持spring mvc、dubbo等测试生成吗？

### ISSUE THREAD

**Issue by ZShUn** [chenhaoxiang/primo#1]
springmvc dubbo 单元测试业务开发大概率会使用

**Comment by chenhaoxiang** [comment]
后面会考虑集成的，但是目前还是在完善阶段。也就是在完善最基本的一些mock功能。大概会在几个版本迭代之后进行一些其他的支持

**Comment by ZShUn** [comment]
好的谢谢
