### ISSUE TITLE
maven 插件不能下载

### ISSUE THREAD

**Issue by angiely1115** [chenhaoxiang/primo#3]
![image](https://user-images.githubusercontent.com/17060364/103254661-27ca0980-49c1-11eb-990c-52a4539cfe5f.png)

Cannot resolve plugin com.uifuture.maven.plugins:agt-maven-plugin:1.1.3

**Comment by chenhaoxiang** [comment]
把本地.m2 / repository下的1.1.3版本删除，然后再刷新拉取下看看，我这边没问题的。中央仓库有这个包

**Comment by chenhaoxiang** [comment]
最近几天会上一个新的版本

**Comment by chenhaoxiang** [comment]
组织id等都会改一下

**Comment by chenhaoxiang** [comment]
已经升级了，欢迎使用啊
```
<plugin> 
    <groupId>wiki.primo.generator</groupId>
    <artifactId>primo-generator-mock-test-maven-plugin</artifactId>
    <version>1.0.0-SNAPSHOT</version> 
        <configuration>
            <testPackageName>wiki.primo.generator.primogeneratormocktestdemo.service.impl</testPackageName> 
        </configuration>
</plugin>
```

**Comment by angiely1115** [comment]
你好，还是下不下来  
![image](https://user-images.githubusercontent.com/17060364/103341134-f89ac180-4ac0-11eb-9a60-1422dd412e7b.png)

**Comment by chenhaoxiang** [comment]
试试最新的版本，我这边下载没问题
